# Description: C++ binary linked with a an external static library
# (the .a & associated headers should be in externalStaticLib/ subfolder)

cc_binary(
    name = "linkedWithExternalStaticLib",
    srcs = glob(["*.cpp", "*.hpp", "externalStaticLib/**"]),
    deps = [],
)